//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deep_EF_SSDT.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SSDTEntities : DbContext
    {
        public SSDTEntities()
            : base("name=SSDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookDetails> BookDetails { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<BooksAuthors> BooksAuthors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<vBook> vBook { get; set; }
    
        public virtual ObjectResult<string> BooksListByAuthor_sp(Nullable<int> authorId)
        {
            var authorIdParameter = authorId.HasValue ?
                new ObjectParameter("authorId", authorId) :
                new ObjectParameter("authorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BooksListByAuthor_sp", authorIdParameter);
        }
    }
}
